apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: blue
        image: vampire2008/capstone:latest
---
apiVersion: v1
kind: Service
metadata:
  name: blue
  namespace: default
  labels:
    app: web
spec:
  type: NodePort
  selector:
    app: web
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 32000