apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: capstone
  region: us-east-1

nodeGroups:
  - name: blue
    instanceType: m5.large
    desiredCapacity: 3
  - name: green
    instanceType: m5.large
    desiredCapacity: 3

